"""
Django settings for neno_lens project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

DEFAULT_ENV = {
    "DEBUG": "True",
    "SECRET_KEY": "django-insecure-y@5(5z7+5eiujs2b)5k$mr67617epht@z_d9v%0n+$n(i8!pya",
    "ALLOWED_HOSTS": "localhost,127.0.0.1,0.0.0.0,[::1],testserver,*.app.github.dev,*.preview.app.github.dev,*.github.dev,*.gitpod.io",
}

DEFAULT_LOCAL_ORIGINS = [
    "http://localhost:8000",
    "https://localhost:8000",
    "http://127.0.0.1:8000",
    "https://127.0.0.1:8000",
    "http://0.0.0.0:8000",
    "https://0.0.0.0:8000",
    "http://[::1]:8000",
    "https://[::1]:8000",
]
DEV_PREVIEW_ORIGINS = [
    "https://*.app.github.dev",
    "https://*.preview.app.github.dev",
    "https://*.github.dev",
    "https://*.gitpod.io",
]
render_hostname = os.environ.get("RENDER_EXTERNAL_HOSTNAME")
RENDER_ORIGINS = []
if render_hostname:
    RENDER_ORIGINS.extend(
        [
            f"https://{render_hostname}",
            f"http://{render_hostname}",
        ]
    )
EXTRA_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",")
    if origin.strip()
]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", DEFAULT_ENV["SECRET_KEY"])

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", DEFAULT_ENV["DEBUG"]).lower() == "true"

host_list = [
    host.strip()
    for host in os.environ.get("ALLOWED_HOSTS", DEFAULT_ENV["ALLOWED_HOSTS"]).split(",")
    if host.strip()
]
if render_hostname:
    host_list.append(render_hostname)
ALLOWED_HOSTS = list(dict.fromkeys(host_list + ["localhost", "127.0.0.1", "0.0.0.0", "[::1]", "testserver", "*.app.github.dev", "*.preview.app.github.dev", "*.github.dev", "*.gitpod.io"]))
CSRF_TRUSTED_ORIGINS = list(dict.fromkeys(DEFAULT_LOCAL_ORIGINS + DEV_PREVIEW_ORIGINS + RENDER_ORIGINS + EXTRA_TRUSTED_ORIGINS + [origin for origin in os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",") if origin.strip()]))


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "dashboard",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "neno_lens.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "neno_lens.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Use HTTPS behind reverse proxies such as Render or Railway
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
