# Generated by Django 6.1.1 on 2026-09-25 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("bible", "Bible"),
                            ("historical", "Historical"),
                            ("research", "Research"),
                            ("technology", "Technology"),
                        ],
                        default="bible",
                        max_length=30,
                    ),
                ),
                ("language", models.CharField(default="sw", max_length=10)),
                ("citation", models.CharField(blank=True, max_length=255)),
                ("url", models.URLField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("trust_level", models.CharField(default="medium", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TechnologyTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("aliases", models.JSONField(blank=True, default=list)),
                ("summary", models.TextField(blank=True)),
                ("category", models.CharField(default="technology", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="BibleVerse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book", models.CharField(max_length=100)),
                ("book_en", models.CharField(blank=True, max_length=100)),
                ("chapter", models.PositiveIntegerField()),
                ("verse", models.PositiveIntegerField()),
                ("text", models.TextField()),
                ("keywords", models.JSONField(blank=True, default=list)),
                ("topics", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {("book", "chapter", "verse")},
            },
        ),
        migrations.CreateModel(
            name="Claim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("claim", models.TextField()),
                ("language", models.CharField(default="sw", max_length=10)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("prophecy", "Prophecy"),
                            ("doctrine", "Doctrine"),
                            ("history", "History"),
                            ("technology", "Technology"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("fact", "Fact"),
                            ("interpretation", "Interpretation"),
                            ("speculation", "Speculation"),
                            ("unknown", "Unknown"),
                        ],
                        default="interpretation",
                        max_length=20,
                    ),
                ),
                ("confidence", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "related_verses",
                    models.ManyToManyField(blank=True, to="dashboard.bibleverse"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalInterpretation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=255)),
                ("era", models.CharField(blank=True, max_length=100)),
                ("summary", models.TextField()),
                (
                    "classification",
                    models.CharField(default="INTERPRETATION", max_length=20),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dashboard.source",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Evidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("FACT", "Fact"),
                            ("INTERPRETATION", "Interpretation"),
                            ("SPECULATION", "Speculation"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("support_strength", models.FloatField(default=0.0)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_items",
                        to="dashboard.claim",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dashboard.source",
                    ),
                ),
            ],
        ),
    ]
